### ISSUE TITLE
Style the account page

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignalDevelopers/ngosi#23]
The account page is where presenters can edit their profile details. At the moment, we have minimal inputs, but they should still be styled to make this page look somewhat decent. 

Current account page.
![Screen Shot 2022-01-04 at 7 38 53 AM](https://user-images.githubusercontent.com/89279465/148060369-8e307374-5270-45d6-9d17-8f1861d8536c.png)

**Comment by Yohanan-Negash** [comment]
The screenshot that was posted at first was a screenshot of the sign-in or login page, so in order to avoid confusion I changed the screenshot you posted above to the actual account page.
