### ISSUE TITLE
Style preso creation form

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignalDevelopers/ngosi#8]
This is where presenters can create a new presentation and then receive their QR code to the preso survey form.

<img width="1276" alt="Screen Shot 2021-12-15 at 5 17 29 PM" src="https://user-images.githubusercontent.com/1715082/146279766-9a0c23ea-bd17-4dd3-8c56-473b61412b93.png">

**Comment by Yohanan-Negash** [comment]
What exactly is the desired style improvement for this page?
